version: 2
registries:
  npm-npmjs:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{ secrets.NPM_TOKEN }}
    replaces-base: true
updates:
  - package-ecosystem: 'npm'
    registries:
      - 'npm-npmjs'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '01:00'
    labels: []
    open-pull-requests-limit: 99
    cooldown:
      default-days: 7
      exclude:
        - "@digabi/*"
